import { siteConfigSchema, type SiteConfig } from './site.config.schema';

const rawConfig = {
  name: 'AletheIA',
  tagline: 'Desarrollo web para negocios locales en México',
  description: 'Creamos sitios web y sistemas digitales para negocios locales en México. Presencia, conversión y automatización.',
  url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://aletheia-starter.vercel.app',
  phone: '+52 7202131181',
  whatsapp: '527202131181',
  email: 'aletheia.webtech@gmail.com',
  address: undefined,
  schedule: 'Lun–Vie 9:00–18:00 (CDMX)',
  social: [
    { label: 'WhatsApp', href: 'https://wa.me/527202131181', icon: 'MessageCircle' },
    { label: 'Instagram', href: 'https://www.instagram.com/aletheia_webtech/', icon: 'Instagram' },
  ],
  nav: [
    { label: 'Servicios', href: '#servicios' },
    { label: 'Sectores', href: '#sectores' },
    { label: 'Precios', href: '#precios' },
    { label: 'Contacto', href: '#contacto' },
  ],
  seo: {
    title: 'AletheIA — Desarrollo web para negocios locales en México',
    description: 'Creamos sitios web y sistemas digitales para negocios locales. Presencia digital, conversión y automatización. Desde $9,900 MXN.',
    ogImage: 'https://aletheia-starter.vercel.app/og-image.jpg',
    keywords: ['desarrollo web México', 'sitios web negocios locales', 'automatización PyMEs', 'diseño web barberías', 'diseño web restaurantes'],
  },
  services: [
    {
      id: 'presencia',
      title: 'Presencia Digital',
      description: 'Diseño personalizado, responsive, SEO técnico básico y deployment. Para negocios sin presencia digital seria.',
      icon: 'Globe',
      features: ['Diseño personalizado', '100% responsive', 'SEO técnico básico', 'WhatsApp integrado', 'Deployment incluido'],
    },
    {
      id: 'conversion',
      title: 'Arquitectura de Conversión',
      description: 'CTAs estratégicos, galería, FAQ, integración de reservas, analítica básica. Para negocios con tráfico que no convierte.',
      icon: 'Target',
      features: ['CTAs estratégicos', 'Galería de trabajos', 'FAQ dinámico', 'Reservas por WhatsApp', 'Analítica básica'],
    },
    {
      id: 'sistema',
      title: 'Sistemas y Automatización',
      description: 'Sistema de reservas, automatizaciones, formularios avanzados, integraciones. Para negocios con volumen y procesos manuales.',
      icon: 'Zap',
      features: ['Sistema de reservas', 'Automatizaciones', 'Formularios avanzados', 'Integraciones API', 'IA si hay caso de uso'],
    },
  ],
  pricing: [
    {
      id: 'presencia',
      name: 'Presencia',
      tagline: 'Tu tarjeta de presentación digital profesional',
      priceFrom: 9900,
      features: [
        'Diseño personalizado (no plantilla)',
        '100% responsive móvil/desktop',
        'Info del negocio: quiénes somos, servicios, ubicación',
        'Botón WhatsApp + formulario de contacto',
        'SEO técnico básico (meta tags, sitemap, schema)',
        'Deployment en Vercel + dominio propio',
        'Entrega en 2–3 semanas',
      ],
      idealFor: 'Negocios con presencia digital pobre o inexistente',
      highlighted: false,
      ctaText: 'Quiero mi web de presencia',
    },
    {
      id: 'conversion',
      name: 'Conversión',
      tagline: 'Convierte tu tráfico en clientes reales',
      priceFrom: 14900,
      features: [
        'Todo lo de Presencia',
        'Arquitectura de conversión (above-the-fold optimizado)',
        'CTAs estratégicos en puntos de decisión',
        'Galería de trabajos/proyectos filtrable',
        'FAQ dinámico con schema.org',
        'Integración WhatsApp con mensaje prellenado',
        'Integración de reservas (Calendly/Google Calendar) cuando aplique',
        'Analítica básica (GA4 + eventos clave)',
        'Entrega en 3–4 semanas',
      ],
      idealFor: 'Negocios que ya tienen tráfico pero necesitan convertirlo',
      highlighted: true,
      ctaText: 'Quiero convertir más',
    },
    {
      id: 'sistema',
      name: 'Sistema',
      tagline: 'Automatiza tu operación y escala sin fricción',
      priceFrom: 24900,
      features: [
        'Todo lo de Conversión',
        'Sistema de reservas propio (disponibilidad, confirmaciones, recordatorios)',
        'Automatizaciones: emails, WhatsApp, estados de pedido/cita',
        'Integraciones: CRM, facturación, pagos, Google Sheets',
        'Formularios avanzados: condicionales, multi-paso, firma digital',
        'Panel de administración simple (sin WordPress)',
        'IA solo si hay caso de uso concreto (clasificación leads, chat FAQ)',
        'Entrega en 5–7 semanas',
      ],
      idealFor: 'Negocios con volumen y procesos manuales que optimizar',
      highlighted: false,
      ctaText: 'Quiero automatizar',
    },
  ],
  nichos: [
    {
      id: 'barberias',
      label: 'Barberías',
      problem: 'Citas por teléfono = llamadas perdidas, doble booking, sin recordatorios',
      solution: 'Reservas por WhatsApp con disponibilidad real, confirmación automática y recordatorio 24h antes',
      icon: 'Scissors',
    },
    {
      id: 'salones',
      label: 'Salones de belleza',
      problem: 'Agenda en papel o notas sueltas, clientes que no vuelven por falta de seguimiento',
      solution: 'Agenda visual 24/7, historial de servicios por cliente, recordatorios y reactivación automática',
      icon: 'Sparkles',
    },
    {
      id: 'esteticas-caninas',
      label: 'Estéticas caninas',
      problem: 'Fichas de mascotas en papel, dueños que olvidan citas, sin control de vacunas/cortes',
      solution: 'Ficha digital por mascota (raza, alergias, corte preferido), recordatorios automáticos, galería antes/después',
      icon: 'Dog',
    },
    {
      id: 'consultorios',
      label: 'Consultorios',
      problem: 'Historia clínica en papel, consentimientos físicos, agenda saturada por llamadas',
      solution: 'Historia clínica digital básica, consentimientos firmados en móvil, auto-agendamiento con filtros por especialidad',
      icon: 'Stethoscope',
    },
    {
      id: 'gimnasios',
      label: 'Gimnasios',
      problem: 'Control de aforo en hoja de papel, reservas de clase por WhatsApp caótico, socios que no renuevan',
      solution: 'Reservas de clase con límite de plazas, check-in QR, alertas de renovación, control de acceso integrado',
      icon: 'Dumbbell',
    },
    {
      id: 'restaurantes',
      label: 'Restaurantes',
      problem: 'Pedidos para llevar por teléfono = errores, reservas de mesa en cuaderno, sin base de clientes',
      solution: 'Carta digital + pedido para llevar (recogida/delivery), reserva de mesa con confirmación, captura de email/WhatsApp para marketing',
      icon: 'UtensilsCrossed',
    },
  ],
};

export const siteConfig = siteConfigSchema.parse(rawConfig);

export type { SiteConfig };